kind: destination
spec:
  name: postgresql
  path: /home/ubuntu/cloudquery/cache/cq-destination-postgresql
  registry: local
  write_mode: "overwrite-delete-stale"
  send_sync_summary: true
  spec:
    connection_string: "${CQ_PG_CONNECTION_STRING}"