# This configuration file defines a destination for CloudQuery to write data to a PostgreSQL database. It specifies the connection string, write mode, and other relevant settings for the destination.
kind: destination
spec:
  name: postgresql
  path: "${CQ_CACHE_DIR}/cq-destination-postgresql"
  registry: local
  write_mode: "overwrite-delete-stale"
  send_sync_summary: true
  spec:
    connection_string: "${CQ_PG_CONNECTION_STRING}"