kind: source
spec:
  name: aws-internal
  path: cloudquery/aws
  registry: github
  version: "v22.19.2"
  tables: ["*"]
  skip_tables:
    - "aws_cloudtrail_events"
  destinations: ["postgresql"]
  spec:
    # Regions to scan: Use ["*"] to crawl all enabled regions, or specify e.g. ["ap-south-1", "us-east-1"]
    regions: ["*"]